kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-volume
  labels:
    type: local
    app: kafka
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka-pv-claim
  labels:
    app: kafka
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
   - port: 9092
# spec:
#   ports:
#   - name: "9092"
#     port: 9092
#     targetPort: 9092
#     nodePort: 30092
#   selector:
#     service: udaconnect-app
#   type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: dinhtin12/kafka:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9092
          # env:
          # - name: POSTGRES_USER
          #   valueFrom:
          #     configMapKeyRef:
          #       name: db-env
          #       key: DB_USERNAME
          # - name: POSTGRES_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: db-secret
          #       key: DB_PASSWORD
          # - name: POSTGRES_DB
          #   valueFrom:
          #     configMapKeyRef:
          #       name: db-env
          #       key: DB_NAME
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: kafka
      volumes:
        - name: kafka
          persistentVolumeClaim:
            claimName: kafka-pv-claim
